anime_list = [
    {"Name": "Sousou no Frieren", "Rating": 9.32, "Creator": "Kanehito Yamada", "Episodes": 28},
    {"Name": "Sousou no Frieren 2nd Season", "Rating": 9.20, "Creator": "Kanehito Yamada", "Episodes": 10},
    {"Name": "Chainsaw Man Movie: Reze-hen", "Rating": 9.10, "Creator": "Tatsuki Fujimoto", "Episodes": 1},
    {"Name": "Fullmetal Alchemist: Brotherhood", "Rating": 9.10, "Creator": "Hiromu Arakawa", "Episodes": 64},
    {"Name": "Steins;Gate", "Rating": 9.07, "Creator": "5pb. & Nitroplus", "Episodes": 24},
    {"Name": "Shingeki no Kyojin Season 3 Part 2", "Rating": 9.05, "Creator": "Hajime Isayama", "Episodes": 10},
    {"Name": "Gintama: The Final", "Rating": 9.05, "Creator": "Hideaki Sorachi", "Episodes": 1},
    {"Name": "Gintama°", "Rating": 9.05, "Creator": "Hideaki Sorachi", "Episodes": 51},
    {"Name": "Hunter x Hunter (2011)", "Rating": 9.03, "Creator": "Yoshihiro Togashi", "Episodes": 148},
    {"Name": "Ginga Eiyuu Densetsu", "Rating": 9.02, "Creator": "Yoshiki Tanaka", "Episodes": 110},
    {"Name": "Gintama'", "Rating": 9.02, "Creator": "Hideaki Sorachi", "Episodes": 51},
    {"Name": "Gintama': Enchousen", "Rating": 9.02, "Creator": "Hideaki Sorachi", "Episodes": 13},
    {"Name": "One Piece Fan Letter", "Rating": 9.02, "Creator": "Eiichiro Oda", "Episodes": 1},
    {"Name": "Bleach: Sennen Kessen-hen", "Rating": 8.98, "Creator": "Tite Kubo", "Episodes": 13},
    {"Name": "Gintama.", "Rating": 8.98, "Creator": "Hideaki Sorachi", "Episodes": 12},
    {"Name": "Kaguya-sama wa Kokurasetai: Ultra Romantic", "Rating": 8.96, "Creator": "Aka Akasaka", "Episodes": 13},
    {"Name": "Fruits Basket: The Final", "Rating": 8.94, "Creator": "Natsuki Takaya", "Episodes": 13},
    {"Name": "Clannad: After Story", "Rating": 8.93, "Creator": "Jun Maeda", "Episodes": 24},
    {"Name": "Gintama", "Rating": 8.93, "Creator": "Hideaki Sorachi", "Episodes": 201},
    {"Name": "Koe no Katachi", "Rating": 8.93, "Creator": "Yoshitoki Oima", "Episodes": 1},
    {"Name": "Kusuriya no Hitorigoto 2nd Season", "Rating": 8.91, "Creator": "Natsu Hyuga", "Episodes": 24},
    {"Name": "Code Geass: Hangyaku no Lelouch R2", "Rating": 8.91, "Creator": "Ichiro Okouchi", "Episodes": 25},
    {"Name": "3-gatsu no Lion 2nd Season", "Rating": 8.90, "Creator": "Chica Umino", "Episodes": 22},
    {"Name": "Gintama Movie 2: Yorozuya yo Eien Nare", "Rating": 8.89, "Creator": "Hideaki Sorachi", "Episodes": 1},
    {"Name": "Monster", "Rating": 8.89, "Creator": "Naoki Urasawa", "Episodes": 74},
    {"Name": "Gintama. Shirogane no Tamashii-hen - Kouhan-sen", "Rating": 8.88, "Creator": "Hideaki Sorachi", "Episodes": 14},
    {"Name": "Owarimonogatari 2nd Season", "Rating": 8.86, "Creator": "Nisio Isin", "Episodes": 7},
    {"Name": "Shingeki no Kyojin: The Final Season - Kanketsu-hen", "Rating": 8.86, "Creator": "Hajime Isayama", "Episodes": 2},
    {"Name": "Kusuriya no Hitorigoto", "Rating": 8.85, "Creator": "Natsu Hyuga", "Episodes": 24},
    {"Name": "Kingdom 3rd Season", "Rating": 8.84, "Creator": "Yasuhisa Hara", "Episodes": 26},
    {"Name": "Violet Evergarden Movie", "Rating": 8.84, "Creator": "Kana Akatsuki", "Episodes": 1},
    {"Name": "Shingeki no Kyojin Movie: Kanketsu-hen - The Last Attack", "Rating": 8.83, "Creator": "Hajime Isayama", "Episodes": 1},
    {"Name": "Kimi no Na wa.", "Rating": 8.83, "Creator": "Makoto Shinkai", "Episodes": 1},
    {"Name": "Vinland Saga Season 2", "Rating": 8.82, "Creator": "Makoto Yukimura", "Episodes": 24},
    {"Name": "Gintama. Shirogane no Tamashii-hen", "Rating": 8.81, "Creator": "Hideaki Sorachi", "Episodes": 12},
    {"Name": "Ashita no Joe 2", "Rating": 8.78, "Creator": "Asao Takamori", "Episodes": 47},
    {"Name": "Hajime no Ippo", "Rating": 8.78, "Creator": "George Morikawa", "Episodes": 75},
    {"Name": "Shingeki no Kyojin: The Final Season", "Rating": 8.78, "Creator": "Hajime Isayama", "Episodes": 16},
    {"Name": "Vinland Saga", "Rating": 8.78, "Creator": "Makoto Yukimura", "Episodes": 24},
    {"Name": "Kizumonogatari III: Reiketsu-hen", "Rating": 8.78, "Creator": "Nisio Isin", "Episodes": 1},
    {"Name": "Mob Psycho 100 II", "Rating": 8.78, "Creator": "ONE", "Episodes": 13},
    {"Name": "Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen Koukou", "Rating": 8.77, "Creator": "Haruichi Furudate", "Episodes": 10},
    {"Name": "Sen to Chihiro no Kamikakushi", "Rating": 8.77, "Creator": "Hayao Miyazaki", "Episodes": 1},
    {"Name": "Shingeki no Kyojin: The Final Season Part 2", "Rating": 8.77, "Creator": "Hajime Isayama", "Episodes": 12},
    {"Name": "Takopii no Genzai", "Rating": 8.76, "Creator": "Taizan 5", "Episodes": 6},
    {"Name": "Monogatari Series: Second Season", "Rating": 8.76, "Creator": "Nisio Isin", "Episodes": 26},
    {"Name": "Cowboy Bebop", "Rating": 8.75, "Creator": "Shinichiro Watanabe", "Episodes": 26},
    {"Name": "Bocchi the Rock!", "Rating": 8.73, "Creator": "Aki Hamaji", "Episodes": 12},
    {"Name": "Boku no Hero Academia: Final Season", "Rating": 8.73, "Creator": "Kohei Horikoshi", "Episodes": 11},
    {"Name": "Kingdom 4th Season", "Rating": 8.73, "Creator": "Yasuhisa Hara", "Episodes": 26}
]